Repository PaloAltoNetworks/pan-cortex-data-lake-python, pull requests merged in 2018-07, with the labels that each got.

#62 Also print request headers and body at debug level 3.
  bin/summit.py
Labels: enhancement

#61 Default R1 to None so don't send body unless specified. Fixes bug
  bin/summit.py
Labels: bug

#60 Enhancements for specifying logging service startTime and endTime.
  bin/summit.py
Labels: enhancement

#63 Switch to json param in client/service methods and remove data param …
  pancloud/directorysync.py
  pancloud/event.py
  pancloud/httpclient.py
  pancloud/logging.py
Labels: breaking-change

#66 params can be None.
  pancloud/logging.py
Labels: bug

#68 Update docs
  docs/conf.py
  docs/guides/credentials.rst
  docs/guides/quickstart.rst
  docs/index.rst
  pancloud/httpclient.py
Labels: documentation

#67 Add support for caching refresh tokens #65
  pancloud/credentials.py
Labels: enhancement

#69 Add Logging Service write API request.
  bin/summit.py
Labels: enhancement

#72 Enforce strict credential resolution
  pancloud/credentials.py
Labels: enhancement

#74 Handle errors before updating credentials #73
  pancloud/credentials.py
Labels: bug

#80 Add PAN_ prefix to envars #75
  docs/guides/credentials.rst
  pancloud/credentials.py
Labels: enhancement
