Repository PaloAltoNetworks/pan-cortex-data-lake-python, pull requests merged in 2018-05, with the labels that each got.

#24 #21 Hotfix 1.0.4
  pancloud/httpclient.py
  pancloud/logging.py
  tests/test_httpclient.py
  tests/test_logging.py
Labels: bug

#25 Add xpoll()
  pancloud/event.py
Labels: enhancement

#23 Add OAuth2 Support #15
  .travis.yml
  Pipfile
  Pipfile.lock
  pancloud/__init__.py
  pancloud/credentials.py
  pancloud/exceptions.py
  pancloud/httpclient.py
  requirements.txt
  tox.ini
Labels: enhancement

#26 Add summit.py: command line interface to the Palo Alto Networks Cloud
  bin/summit.py
Labels: enhancement

#27 Remove erroneous -T option
  bin/summit.py
Labels: bug

#33 Rework to make --R[012] processing context/order dependent. This
  bin/summit.py
Labels: enhancement

#32 Add params kwarg to count method
  pancloud/directorysync.py
Labels: bug

#28 Add auto_retry feature
  pancloud/httpclient.py
Labels: enhancement

#29 Update examples #16
  examples/credentials_generate.py
  examples/credentials_test.py
  examples/directory_attributes.py
  examples/directory_count.py
  examples/event_ack.py
  examples/event_get_filters.py
  examples/event_nack.py
  examples/event_poll.py
  examples/event_set_filters.py
  examples/logging_iter_poll.py
  examples/logging_poll_all.py
  examples/logging_query.py
  examples/shared_session.py
  pancloud/credentials.py
Labels: enhancement

#34 Hotfix 1.0.5
  examples/credentials_generate.py
  pancloud/credentials.py
Labels: bug

#36 Add initial Credentials() class support.
  bin/summit.py
Labels: enhancement

#37 Set permissions on creation of credentials file
  pancloud/credentials.py
Labels: bug

#43 Change logging xpoll() to return entire log entry instead of just
  pancloud/logging.py
Labels: enhancement

#41 Update docs
  README.rst
  docs/guides/credentials.rst
  docs/guides/quickstart.rst
  docs/index.rst
  docs/source/modules.rst
  docs/source/pancloud.adapters.rst
  docs/source/pancloud.rst
  docs/usage.rst
  pancloud/credentials.py
  requirements_dev.txt
Labels: documentation

#42 Add storage adapter feature
  Pipfile.lock
  pancloud/adapters/__init__.py
  pancloud/adapters/adapter.py
  pancloud/adapters/tinydb_adapter.py
  pancloud/credentials.py
  pancloud/httpclient.py
  setup.py
  tox.ini
Labels: enhancement

#45 Missing print and exit functions after event poll().
  bin/summit.py
Labels: bug

#46 Should be checking start/end options for None; allows to specify time
  bin/summit.py
Labels: bug
