Repository PaloAltoNetworks/pan-cortex-data-lake-python, pull requests merged in 2018-08, with the labels that each got.

#83 Add argument to xpoll(): pause (float): Seconds to sleep between poll
  pancloud/event.py
Labels: enhancement

#84 Configure JMESPath custom function isotime(), which prints Epoch
  bin/summit.py
Labels: enhancement

#79 Update headers instead of overriding #78
  pancloud/__init__.py
  pancloud/httpclient.py
Labels: bug

#88 Refactor how authorization header is updated #86
  pancloud/httpclient.py
Labels: bug

#89 Return None instead of empty str #81
  pancloud/adapters/tinydb_adapter.py
Labels: bug

#90 Add support for custom read/write credentials path #87
  .travis.yml
  pancloud/adapters/tinydb_adapter.py
  pancloud/credentials.py
Labels: enhancement

#95 Update -E --ack,nack,poll options usage to be accurate.
  bin/summit.py
Labels: documentation

#100 Add __repr__ to Credentials class and mask secrets #94
  pancloud/credentials.py
Labels: enhancement

#99 Generate new state each time get_authorization_url() is called #97
  pancloud/credentials.py
Labels: enhancement
